AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sofa006LambdaImageGeneration

  Sample SAM Template for sofa006LambdaImageGeneration

  '
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  SofaImageGenerationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://pgr301-bucket-sofa006/3e9b726c621650604092837838617991
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          BUCKET_NAME: pgr301-couch-explorers
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
        - Effect: Allow
          Action:
          - s3:PutObject
          Resource: arn:aws:s3:::pgr301-couch-explorers/5/*
        - Effect: Allow
          Action:
          - bedrock:InvokeModel
          Resource: '*'
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /generate
            Method: post
    Metadata:
      SamResourceId: SofaImageGenerationFunction
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for the image generation
      function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/
