on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./sofa006LambdaImageGeneration
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset
      - run: sam package --s3-bucket pgr301-bucket-sofa006 --output-template-file packaged.yaml
      - run: sam deploy --no-confirm-changeset --template-file packaged.yaml --stack-name sofastack --capabilities CAPABILITY_IAM